Fix: Allow timzeone to be changed
unifi-core is unable to change timezone due to /etc/timezone /etc/localtime being writable only by root. This can result in cameras being updated with the incorrect timezone.

```
error: Failed to change the timezone: Command failed: ubnt-systool timezone Pacific/Auckland
Failed to set time zone: Access denied
rm: cannot remove '/etc/localtime': Permission denied
cp: cannot remove '/etc/localtime': Permission denied
/sbin/ubnt-systool: 234: eval: cannot create /etc/timezone: Permission denied
```